# Generated by Django 6.0.7 on 2026-08-05 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id_section', models.AutoField(primary_key=True, serialize=False)),
                ('nom_section', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'SECTION',
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id_compte', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('mot_de_passe_hash', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut_compte', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20)),
                ('est_admin', models.BooleanField(default=False)),
                ('compte_nommant', models.ForeignKey(blank=True, db_column='id_compte_nommant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_nommes', to='adhesion.compte')),
            ],
            options={
                'db_table': 'COMPTE',
            },
        ),
        migrations.CreateModel(
            name='Controleur',
            fields=[
                ('id_controleur', models.AutoField(primary_key=True, serialize=False)),
                ('zone_affectation', models.CharField(blank=True, max_length=100, null=True)),
                ('date_nomination', models.DateField()),
                ('compte', models.OneToOneField(db_column='id_compte', on_delete=django.db.models.deletion.CASCADE, related_name='controleur', to='adhesion.compte')),
            ],
            options={
                'db_table': 'CONTROLEUR',
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id_evenement', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150)),
                ('date_evenement', models.DateTimeField()),
                ('lieu', models.CharField(max_length=150)),
                ('type_evenement', models.CharField(choices=[('MEETING', 'Meeting'), ('CONGRES', 'Congrès'), ('AG', 'Assemblée générale')], max_length=20)),
                ('compte_organisateur', models.ForeignKey(db_column='id_compte_organisateur', on_delete=django.db.models.deletion.PROTECT, related_name='evenements_organises', to='adhesion.compte')),
            ],
            options={
                'db_table': 'EVENEMENT',
            },
        ),
        migrations.CreateModel(
            name='Jeton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(editable=False, max_length=64, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jeton', to='adhesion.compte')),
            ],
            options={
                'db_table': 'JETON',
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id_action', models.AutoField(primary_key=True, serialize=False)),
                ('type_action', models.CharField(max_length=50)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('compte_auteur', models.ForeignKey(db_column='id_compte_auteur', on_delete=django.db.models.deletion.PROTECT, related_name='actions_journalisees', to='adhesion.compte')),
            ],
            options={
                'db_table': 'JOURNAL_AUDIT',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id_membre', models.AutoField(primary_key=True, serialize=False)),
                ('numero_adherent', models.CharField(max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_membres/')),
                ('date_adhesion', models.DateField()),
                ('statut_adhesion', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EXPIRE', 'Expiré')], default='ACTIF', max_length=20)),
                ('compte', models.OneToOneField(db_column='id_compte', on_delete=django.db.models.deletion.CASCADE, related_name='membre', to='adhesion.compte')),
                ('parrain', models.ForeignKey(blank=True, db_column='id_parrain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to='adhesion.membre')),
                ('section', models.ForeignKey(db_column='id_section', on_delete=django.db.models.deletion.PROTECT, related_name='membres', to='adhesion.section')),
            ],
            options={
                'db_table': 'MEMBRE',
            },
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id_cotisation', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('periode_couverte', models.CharField(max_length=20)),
                ('membre', models.ForeignKey(db_column='id_membre', on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='adhesion.membre')),
            ],
            options={
                'db_table': 'COTISATION',
            },
        ),
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id_carte', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(unique=True)),
                ('type_carte', models.CharField(choices=[('QR', 'QR Code'), ('NFC', 'Puce NFC')], max_length=10)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('statut_carte', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOQUEE', 'Bloquée'), ('PERDUE', 'Perdue')], default='ACTIVE', max_length=20)),
                ('id_version_cle', models.PositiveSmallIntegerField()),
                ('membre', models.ForeignKey(db_column='id_membre', on_delete=django.db.models.deletion.CASCADE, related_name='cartes', to='adhesion.membre')),
            ],
            options={
                'db_table': 'CARTE',
            },
        ),
        migrations.CreateModel(
            name='Participe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_arrivee', models.DateTimeField()),
                ('methode_scan', models.CharField(choices=[('QR', 'QR Code'), ('NFC', 'Puce NFC'), ('MANUEL', 'Recherche manuelle')], max_length=10)),
                ('controleur_scan', models.ForeignKey(db_column='id_controleur_scan', on_delete=django.db.models.deletion.PROTECT, related_name='scans_effectues', to='adhesion.controleur')),
                ('evenement', models.ForeignKey(db_column='id_evenement', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='adhesion.evenement')),
                ('membre', models.ForeignKey(db_column='id_membre', on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='adhesion.membre')),
            ],
            options={
                'db_table': 'PARTICIPE',
                'unique_together': {('membre', 'evenement')},
            },
        ),
    ]
