# Generated by Django 6.0.7 on 2026-08-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='doit_changer_mot_de_passe',
            field=models.BooleanField(default=False),
        ),
    ]
