# Generated by Django 6.0.7 on 2026-08-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0002_compte_doit_changer_mot_de_passe'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='est_termine',
            field=models.BooleanField(default=False),
        ),
    ]
