# Generated by Django 6.0.7 on 2026-08-10 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0003_evenement_date_fin_evenement_est_termine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='date_evenement',
        ),
        migrations.AlterField(
            model_name='evenement',
            name='type_evenement',
            field=models.CharField(choices=[('MEETING', 'Meeting'), ('CONGRES', 'Congrès'), ('AG', 'Assemblée générale'), ('FORMATION', 'Formation'), ('DISTRIBUTION_MATERIEL', 'Distribution de matériel'), ('MISSION_MEDICALE', 'Mission médicale'), ('AUTRE', 'Autre')], max_length=30),
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id_seance', models.AutoField(primary_key=True, serialize=False)),
                ('date_seance', models.DateTimeField()),
                ('numero_ordre', models.PositiveSmallIntegerField(default=1)),
                ('evenement', models.ForeignKey(db_column='id_evenement', on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='adhesion.evenement')),
            ],
            options={
                'db_table': 'SEANCE',
                'ordering': ['numero_ordre'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='participe',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='participe',
            name='seance',
            field=models.ForeignKey(db_column='id_seance', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='adhesion.seance'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='participe',
            unique_together={('membre', 'seance')},
        ),
        migrations.RemoveField(
            model_name='participe',
            name='evenement',
        ),
    ]
