# Generated by Django 6.0.7 on 2026-08-10 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0004_remove_evenement_date_evenement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id_formation', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('domaine', models.CharField(blank=True, max_length=100, null=True)),
                ('duree_heures', models.PositiveIntegerField(blank=True, help_text='Durée totale indicative en heures', null=True)),
            ],
            options={
                'db_table': 'FORMATION',
            },
        ),
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('id_cohorte', models.AutoField(primary_key=True, serialize=False)),
                ('code_cohorte', models.CharField(help_text='Ex: "Couture-2026-T1"', max_length=50, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lieu', models.CharField(max_length=150)),
                ('formateur', models.CharField(blank=True, max_length=150, null=True)),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée')], default='PLANIFIEE', max_length=20)),
                ('formation', models.ForeignKey(db_column='id_formation', on_delete=django.db.models.deletion.PROTECT, related_name='cohortes', to='adhesion.formation')),
            ],
            options={
                'db_table': 'COHORTE',
            },
        ),
        migrations.CreateModel(
            name='SeanceCohorte',
            fields=[
                ('id_seance_cohorte', models.AutoField(primary_key=True, serialize=False)),
                ('date_seance', models.DateTimeField()),
                ('numero_ordre', models.PositiveSmallIntegerField(default=1)),
                ('cohorte', models.ForeignKey(db_column='id_cohorte', on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='adhesion.cohorte')),
            ],
            options={
                'db_table': 'SEANCE_COHORTE',
                'ordering': ['numero_ordre'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionCohorte',
            fields=[
                ('id_inscription', models.AutoField(primary_key=True, serialize=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('INSCRIT', 'Inscrit'), ('CONFIRME', 'Confirmé'), ('ABANDON', 'Abandon')], default='INSCRIT', max_length=20)),
                ('cohorte', models.ForeignKey(db_column='id_cohorte', on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='adhesion.cohorte')),
                ('membre', models.ForeignKey(db_column='id_membre', on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_cohortes', to='adhesion.membre')),
            ],
            options={
                'db_table': 'INSCRIPTION_COHORTE',
                'unique_together': {('membre', 'cohorte')},
            },
        ),
        migrations.CreateModel(
            name='PresenceCohorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_arrivee', models.DateTimeField()),
                ('methode_scan', models.CharField(choices=[('QR', 'QR Code'), ('NFC', 'Puce NFC'), ('MANUEL', 'Recherche manuelle')], max_length=10)),
                ('controleur_scan', models.ForeignKey(db_column='id_controleur_scan', on_delete=django.db.models.deletion.PROTECT, related_name='scans_cohortes', to='adhesion.controleur')),
                ('membre', models.ForeignKey(db_column='id_membre', on_delete=django.db.models.deletion.CASCADE, related_name='presences_cohortes', to='adhesion.membre')),
                ('seance_cohorte', models.ForeignKey(db_column='id_seance_cohorte', on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='adhesion.seancecohorte')),
            ],
            options={
                'db_table': 'PRESENCE_COHORTE',
                'unique_together': {('membre', 'seance_cohorte')},
            },
        ),
    ]
