# Generated by Django 6.0.7 on 2026-08-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0005_formation_cohorte_seancecohorte_inscriptioncohorte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='type_evenement',
            field=models.CharField(choices=[('MEETING', 'Meeting'), ('CONGRES', 'Congrès'), ('AG', 'Assemblée générale'), ('DISTRIBUTION_MATERIEL', 'Distribution de matériel'), ('MISSION_MEDICALE', 'Mission médicale'), ('AUTRE', 'Autre')], max_length=30),
        ),
    ]
