# Generated by Django 6.1 on 2026-08-21 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0006_alter_evenement_type_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='seancecohorte',
            name='formateur_seance',
            field=models.CharField(blank=True, help_text='Laisser vide pour reprendre le formateur par défaut de la cohorte', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='seancecohorte',
            name='heure_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seancecohorte',
            name='lieu',
            field=models.CharField(blank=True, help_text='Laisser vide pour reprendre le lieu par défaut de la cohorte', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='seancecohorte',
            name='titre_seance',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='seancecohorte',
            name='type_seance',
            field=models.CharField(choices=[('COURS', 'Cours'), ('TD', 'Travaux dirigés'), ('TP', 'Travaux pratiques'), ('EXAMEN', 'Examen')], default='COURS', max_length=10),
        ),
        migrations.AlterField(
            model_name='seancecohorte',
            name='date_seance',
            field=models.DateTimeField(help_text='Date + heure de début'),
        ),
        migrations.CreateModel(
            name='ParticipantCohorte',
            fields=[
                ('id_participant', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_carte_identite', models.CharField(blank=True, max_length=50, null=True)),
                ('uuid', models.UUIDField(unique=True)),
                ('id_version_cle', models.PositiveSmallIntegerField()),
                ('source', models.CharField(choices=[('EXCEL', 'Import Excel'), ('MANUEL', 'Ajout manuel'), ('COMPTE', 'Auto-inscription via compte')], max_length=10)),
                ('statut', models.CharField(choices=[('INSCRIT', 'Inscrit'), ('CONFIRME', 'Confirmé'), ('ABANDON', 'Abandon')], default='INSCRIT', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('cohorte', models.ForeignKey(db_column='id_cohorte', on_delete=django.db.models.deletion.CASCADE, related_name='participants_cohorte', to='adhesion.cohorte')),
                ('membre', models.ForeignKey(blank=True, db_column='id_membre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations_cohortes', to='adhesion.membre')),
            ],
            options={
                'db_table': 'PARTICIPANT_COHORTE',
            },
        ),
        migrations.AlterUniqueTogether(
            name='presencecohorte',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='presencecohorte',
            name='participant',
            field=models.ForeignKey(db_column='id_participant', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='adhesion.participantcohorte'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='presencecohorte',
            unique_together={('participant', 'seance_cohorte')},
        ),
        migrations.DeleteModel(
            name='InscriptionCohorte',
        ),
        migrations.RemoveField(
            model_name='presencecohorte',
            name='membre',
        ),
    ]
