# Generated by Django 6.1 on 2026-08-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0007_compte_telephone_seancecohorte_formateur_seance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohorte',
            name='capacite_max',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre max de participants (vide = illimité)', null=True),
        ),
        migrations.AddField(
            model_name='cohorte',
            name='capacite_min',
            field=models.PositiveIntegerField(blank=True, help_text="Seuil minimal pour maintenir la session (en dessous, envisager l'annulation)", null=True),
        ),
        migrations.AddField(
            model_name='cohorte',
            name='conditions_annulation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cohorte',
            name='date_limite_inscription',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cohorte',
            name='financeur',
            field=models.CharField(blank=True, help_text='Bailleur associé, si formation subventionnée', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cohorte',
            name='materiel_necessaire',
            field=models.TextField(blank=True, help_text='Vidéoprojecteur, ordinateurs, salle équipée...', null=True),
        ),
        migrations.AddField(
            model_name='cohorte',
            name='numero_convention',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cohorte',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vide ou 0 = gratuite', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cohorte',
            name='prix_adherent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarif préférentiel adhérent, si différent du prix standard', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='code_reference',
            field=models.CharField(blank=True, help_text='Ex: "FORM-2026-001", pour le suivi interne', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='prerequis',
            field=models.TextField(blank=True, help_text='Diplôme, niveau requis, matériel à apporter...', null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='public_cible',
            field=models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé'), ('TOUS', 'Tous niveaux')], default='TOUS', max_length=20),
        ),
        migrations.AddField(
            model_name='formation',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIEE', 'Publiée'), ('COMPLETE', 'Complète'), ('ANNULEE', 'Annulée'), ('TERMINEE', 'Terminée')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='cohorte',
            name='lieu',
            field=models.CharField(help_text='Adresse/salle, ou "à définir"', max_length=150),
        ),
        migrations.AlterField(
            model_name='formation',
            name='description',
            field=models.TextField(blank=True, help_text='Description et objectifs pédagogiques', null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='domaine',
            field=models.CharField(blank=True, help_text='Catégorie/thématique (ex: informatique, langues, gestion de projet)', max_length=100, null=True),
        ),
    ]
