# Generated by Django 6.1 on 2026-08-22 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0008_cohorte_capacite_max_cohorte_capacite_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id_participant', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_carte_identite', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_badge', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_participants/')),
                ('uuid', models.UUIDField(unique=True)),
                ('id_version_cle', models.PositiveSmallIntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('membre', models.OneToOneField(blank=True, db_column='id_membre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_externe', to='adhesion.membre')),
            ],
            options={
                'db_table': 'PARTICIPANT',
            },
        ),
        migrations.AlterField(
            model_name='presencecohorte',
            name='participant',
            field=models.ForeignKey(db_column='id_participant', on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='adhesion.participant'),
        ),
        migrations.CreateModel(
            name='InscriptionCohorte',
            fields=[
                ('id_inscription', models.AutoField(primary_key=True, serialize=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('INSCRIT', 'Inscrit'), ('CONFIRME', 'Confirmé'), ('ABANDON', 'Abandon')], default='INSCRIT', max_length=20)),
                ('source', models.CharField(choices=[('EXCEL', 'Import Excel'), ('MANUEL', 'Ajout manuel'), ('COMPTE', 'Auto-inscription via compte')], max_length=10)),
                ('cohorte', models.ForeignKey(db_column='id_cohorte', on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='adhesion.cohorte')),
                ('participant', models.ForeignKey(db_column='id_participant', on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='adhesion.participant')),
            ],
            options={
                'db_table': 'INSCRIPTION_COHORTE',
                'unique_together': {('participant', 'cohorte')},
            },
        ),
        migrations.DeleteModel(
            name='ParticipantCohorte',
        ),
    ]
