# Generated by Django 6.1 on 2026-08-22 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0009_participant_alter_presencecohorte_participant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotisation_active', models.BooleanField(default=False, help_text='Activer la gestion des cotisations (masquée par défaut)')),
                ('montant_cotisation_annuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seuil_certification_defaut', models.PositiveIntegerField(default=75, help_text='Seuil de présence par défaut pour la certification (%)')),
                ('duree_suivi_defaut_jours', models.PositiveIntegerField(default=180, help_text='Durée de suivi post-formation par défaut (en jours)')),
                ('nom_association', models.CharField(default='AP2A', max_length=200)),
                ('slogan', models.CharField(blank=True, max_length=300, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('adresse', models.TextField(blank=True, null=True)),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone_contact', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': "Configuration de l'association",
                'verbose_name_plural': "Configuration de l'association",
                'db_table': 'CONFIG_ASSOCIATION',
            },
        ),
        migrations.CreateModel(
            name='ParticipationAction',
            fields=[
                ('id_participation', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours de suivi'), ('TERMINE', 'Terminé avec succès'), ('ABANDON', 'Abandonné')], default='EN_ATTENTE', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_maj', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('type_aide_recue', models.CharField(blank=True, help_text="Description de l'aide concrète fournie", max_length=200, null=True)),
            ],
            options={
                'db_table': 'PARTICIPATION_ACTION',
            },
        ),
        migrations.AddField(
            model_name='cohorte',
            name='duree_suivi_jours',
            field=models.PositiveIntegerField(blank=True, help_text='Durée du suivi post-formation en jours, définie par les admins (vide = pas de suivi)', null=True),
        ),
        migrations.AddField(
            model_name='cohorte',
            name='seuil_certification',
            field=models.PositiveIntegerField(default=75, help_text="Pourcentage minimum de présence pour obtenir le certificat (laissé à l'appréciation des organisateurs)"),
        ),
        migrations.AddField(
            model_name='compte',
            name='est_super_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evenement',
            name='capacite_max',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre max de participants (vide = illimité)', null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='mode_inscription',
            field=models.CharField(choices=[('OUVERT', 'Ouvert à tous les membres'), ('SUR_INSCRIPTION', 'Sur inscription préalable')], default='OUVERT', max_length=20),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='type_evenement',
            field=models.CharField(choices=[('MEETING', 'Meeting'), ('CONGRES', 'Congrès'), ('AG', 'Assemblée générale'), ('REUNION', 'Réunion'), ('GALA', 'Gala'), ('DISTRIBUTION_MATERIEL', 'Distribution de matériel'), ('MISSION_MEDICALE', 'Mission médicale'), ('AUTRE', 'Autre')], max_length=30),
        ),
        migrations.CreateModel(
            name='ActionSociale',
            fields=[
                ('id_action', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150)),
                ('type_action', models.CharField(choices=[('COMMERCE', 'Aide à la création de commerce'), ('ATELIER', "Aide à l'ouverture d'atelier"), ('MEDICAL', 'Consultation / traitement médical'), ('AUTRE', 'Autre action sociale')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=150, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20)),
                ('compte_organisateur', models.ForeignKey(db_column='id_compte_organisateur', on_delete=django.db.models.deletion.PROTECT, related_name='actions_sociales_organisees', to='adhesion.compte')),
            ],
            options={
                'db_table': 'ACTION_SOCIALE',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id_beneficiaire', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('numero_identification', models.CharField(blank=True, help_text="Numéro de carte d'identité (optionnel)", max_length=50, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('membre', models.OneToOneField(blank=True, db_column='id_membre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaire', to='adhesion.membre')),
            ],
            options={
                'db_table': 'BENEFICIAIRE',
            },
        ),
        migrations.CreateModel(
            name='DetailAtelier',
            fields=[
                ('participation', models.OneToOneField(db_column='id_participation', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail_atelier', serialize=False, to='adhesion.participationaction')),
                ('domaine_atelier', models.CharField(max_length=150)),
                ('equipement_fourni', models.TextField(blank=True, help_text='Liste du matériel/équipement fourni', null=True)),
                ('local_mis_a_disposition', models.BooleanField(default=False)),
                ('atelier_operationnel', models.BooleanField(default=False, help_text="L'atelier est-il effectivement ouvert et en activité ?")),
            ],
            options={
                'db_table': 'DETAIL_ATELIER',
            },
        ),
        migrations.CreateModel(
            name='DetailCommerce',
            fields=[
                ('participation', models.OneToOneField(db_column='id_participation', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail_commerce', serialize=False, to='adhesion.participationaction')),
                ('type_commerce', models.CharField(max_length=150)),
                ('localisation', models.CharField(blank=True, max_length=200, null=True)),
                ('capital_depart_fourni', models.BooleanField(default=False)),
                ('montant_accompagnement', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commerce_operationnel', models.BooleanField(default=False, help_text='Le commerce est-il effectivement ouvert et en activité ?')),
            ],
            options={
                'db_table': 'DETAIL_COMMERCE',
            },
        ),
        migrations.CreateModel(
            name='DetailMedical',
            fields=[
                ('participation', models.OneToOneField(db_column='id_participation', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail_medical', serialize=False, to='adhesion.participationaction')),
                ('date_consultation', models.DateField()),
                ('type_soin', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('TRAITEMENT', 'Traitement'), ('MEDICAMENTS', 'Remise de médicaments'), ('CONSULTATION_TRAITEMENT', 'Consultation + traitement')], max_length=30)),
                ('medecin_referent', models.CharField(blank=True, max_length=150, null=True)),
                ('traitement_fourni', models.BooleanField(default=False)),
                ('notes_suivi', models.TextField(blank=True, help_text='Notes de suivi (sans information médicale identifiable)', null=True)),
            ],
            options={
                'db_table': 'DETAIL_MEDICAL',
            },
        ),
        migrations.AddField(
            model_name='participationaction',
            name='action',
            field=models.ForeignKey(db_column='id_action', on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='adhesion.actionsociale'),
        ),
        migrations.AddField(
            model_name='participationaction',
            name='beneficiaire',
            field=models.ForeignKey(db_column='id_beneficiaire', on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='adhesion.beneficiaire'),
        ),
        migrations.CreateModel(
            name='InviteExterne',
            fields=[
                ('id_invite', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('organisation', models.CharField(blank=True, max_length=150, null=True)),
                ('est_present', models.BooleanField(default=False)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(db_column='id_evenement', on_delete=django.db.models.deletion.CASCADE, related_name='invites_externes', to='adhesion.evenement')),
            ],
            options={
                'db_table': 'INVITE_EXTERNE',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('corps', models.TextField()),
                ('type_notification', models.CharField(choices=[('INFO', 'Information'), ('RAPPEL', 'Rappel'), ('ALERTE', 'Alerte'), ('SUCCES', 'Succès')], default='INFO', max_length=10)),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lien_action', models.CharField(blank=True, help_text="Route ou identifiant pour navigation dans l'app", max_length=200, null=True)),
                ('compte_destinataire', models.ForeignKey(db_column='id_compte_destinataire', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='adhesion.compte')),
            ],
            options={
                'db_table': 'NOTIFICATION',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SuiviPostFormation',
            fields=[
                ('id_suivi', models.AutoField(primary_key=True, serialize=False)),
                ('date_suivi', models.DateField()),
                ('moyen_contact', models.CharField(choices=[('VISITE', 'Visite terrain'), ('APPEL', 'Appel téléphonique'), ('MESSAGE', 'Message (SMS/WhatsApp)')], max_length=10)),
                ('kit_remis', models.BooleanField(default=False)),
                ('certificat_emis', models.BooleanField(default=False)),
                ('activite_lancee', models.BooleanField(default=False)),
                ('type_activite', models.CharField(blank=True, help_text="Si activité lancée : quel type d'activité", max_length=150, null=True)),
                ('localisation_activite', models.CharField(blank=True, max_length=200, null=True)),
                ('difficultes', models.TextField(blank=True, help_text='Difficultés rencontrées par le participant', null=True)),
                ('niveau_satisfaction', models.PositiveSmallIntegerField(blank=True, help_text='Note de 1 (très insatisfait) à 5 (très satisfait)', null=True)),
                ('recommandations', models.TextField(blank=True, null=True)),
                ('statut_global', models.CharField(choices=[('EN_COURS', 'Suivi en cours'), ('STABLE', 'Situation stable'), ('ABANDONNE', 'Participant a abandonné'), ('SUCCES', 'Objectif atteint')], default='EN_COURS', max_length=20)),
                ('cohorte', models.ForeignKey(db_column='id_cohorte', on_delete=django.db.models.deletion.CASCADE, related_name='suivis_post_formation', to='adhesion.cohorte')),
                ('effectue_par', models.ForeignKey(db_column='id_compte_effectuant', on_delete=django.db.models.deletion.PROTECT, related_name='suivis_effectues', to='adhesion.compte')),
                ('participant', models.ForeignKey(db_column='id_participant', on_delete=django.db.models.deletion.CASCADE, related_name='suivis_post_formation', to='adhesion.participant')),
            ],
            options={
                'db_table': 'SUIVI_POST_FORMATION',
                'ordering': ['-date_suivi'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmationEvenement',
            fields=[
                ('id_confirmation', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('CONFIRME', 'Confirmé'), ('LISTE_ATTENTE', "En liste d'attente"), ('ANNULE', 'Annulé par le membre')], default='CONFIRME', max_length=20)),
                ('date_confirmation', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(db_column='id_evenement', on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='adhesion.evenement')),
                ('membre', models.ForeignKey(db_column='id_membre', on_delete=django.db.models.deletion.CASCADE, related_name='confirmations_evenements', to='adhesion.membre')),
            ],
            options={
                'db_table': 'CONFIRMATION_EVENEMENT',
                'unique_together': {('membre', 'evenement')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='participationaction',
            unique_together={('beneficiaire', 'action')},
        ),
        migrations.CreateModel(
            name='PermissionAdmin',
            fields=[
                ('id_permission', models.AutoField(primary_key=True, serialize=False)),
                ('code_permission', models.CharField(choices=[('GERER_MEMBRES', 'Gérer les membres'), ('GERER_EVENEMENTS', 'Gérer les événements'), ('GERER_FORMATIONS', 'Gérer les formations et cohortes'), ('GERER_ACTIONS_SOCIALES', 'Gérer les actions sociales'), ('GERER_CONTROLEURS', 'Gérer les contrôleurs'), ('VOIR_RAPPORTS', 'Voir les rapports et statistiques'), ('IMPORTER_DONNEES', 'Importer des données Excel'), ('GERER_SUIVI', 'Gérer le suivi post-formation')], max_length=30)),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('attribue_par', models.ForeignKey(blank=True, db_column='id_compte_attribuant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_attribuees', to='adhesion.compte')),
                ('compte', models.ForeignKey(db_column='id_compte', on_delete=django.db.models.deletion.CASCADE, related_name='permissions_admin', to='adhesion.compte')),
            ],
            options={
                'db_table': 'PERMISSION_ADMIN',
                'unique_together': {('compte', 'code_permission')},
            },
        ),
    ]
