# Generated by Django 6.1 on 2026-08-23 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0010_configassociation_participationaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohorte',
            name='est_payante',
            field=models.BooleanField(default=True, help_text='Désactivé = formation gratuite, les champs prix sont ignorés'),
        ),
        migrations.AddField(
            model_name='cohorte',
            name='membres_cibles',
            field=models.ManyToManyField(blank=True, help_text="Pertinent seulement si public_cible_type='SPECIFIQUE'", related_name='cohortes_ciblees', to='adhesion.membre'),
        ),
        migrations.AddField(
            model_name='cohorte',
            name='public_cible_type',
            field=models.CharField(choices=[('TOUS', 'Tous les membres'), ('SPECIFIQUE', 'Sélection de membres')], default='TOUS', max_length=20),
        ),
        migrations.AddField(
            model_name='controleur',
            name='evenement_assigne',
            field=models.ForeignKey(blank=True, db_column='id_evenement_assigne', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controleurs_assignes', to='adhesion.evenement'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='membres_cibles',
            field=models.ManyToManyField(blank=True, related_name='evenements_cibles', to='adhesion.membre'),
        ),
        migrations.AddField(
            model_name='inscriptioncohorte',
            name='date_distribution_kit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscriptioncohorte',
            name='kit_distribue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='mode_inscription',
            field=models.CharField(choices=[('OUVERT', 'Ouvert à tous les membres'), ('SUR_INSCRIPTION', 'Sur inscription préalable'), ('RESTREINT', 'Restreint à une sélection de membres')], default='OUVERT', max_length=20),
        ),
    ]
