# Generated by Django 6.1 on 2026-08-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0011_cohorte_est_payante_cohorte_membres_cibles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='est_annule',
            field=models.BooleanField(default=False),
        ),
    ]
