# Generated by Django 6.1 on 2026-08-23 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0012_evenement_est_annule'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionsociale',
            name='contenu_don',
            field=models.TextField(blank=True, help_text="Ce qui est distribué (ex: 25kg de riz, 5L d'huile, fournitures, semences...)", null=True),
        ),
        migrations.AddField(
            model_name='cohorte',
            name='contenu_kit',
            field=models.TextField(blank=True, help_text='Description du matériel et fournitures contenus dans le kit remis aux participants', null=True),
        ),
        migrations.AddField(
            model_name='detailmedical',
            name='a_ete_visite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detailmedical',
            name='date_traitement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailmedical',
            name='date_visite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailmedical',
            name='description_besoin_traitement',
            field=models.TextField(blank=True, help_text='Besoins de traitement ou orientation identifiés', null=True),
        ),
        migrations.AddField(
            model_name='detailmedical',
            name='necessite_traitement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detailmedical',
            name='traitement_effectue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evenement',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PROGRAMME', 'Programmé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PROGRAMME', max_length=20),
        ),
        migrations.AddField(
            model_name='inscriptioncohorte',
            name='certificat_delivre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscriptioncohorte',
            name='date_emission_certificat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscriptioncohorte',
            name='remis_par',
            field=models.ForeignKey(blank=True, db_column='id_compte_remettant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kits_remis', to='adhesion.compte'),
        ),
        migrations.AddField(
            model_name='participationaction',
            name='date_reception_don',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participationaction',
            name='don_recu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actionsociale',
            name='type_action',
            field=models.CharField(choices=[('DON', 'Distribution de dons alimentaires / matériels'), ('COMMERCE', 'Aide à la création de commerce'), ('ATELIER', "Aide à l'ouverture d'atelier"), ('MEDICAL', 'Consultation / traitement médical'), ('AUTRE', 'Autre action sociale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cohorte',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PROGRAMMEE', 'Programmée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PROGRAMMEE', max_length=20),
        ),
    ]
