# Generated by Django 6.1 on 2026-08-24 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0013_actionsociale_contenu_don_cohorte_contenu_kit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohorte',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PROGRAMMEE', 'Programmée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20),
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id_kit', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('contenu', models.TextField(help_text='Description du matériel et fournitures du kit')),
                ('type_cible', models.CharField(choices=[('FORMATION', 'Toute une formation'), ('COHORTE', 'Une cohorte précise'), ('PARTICIPANTS', "Certains participants d'une cohorte")], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cohorte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='adhesion.cohorte')),
                ('cree_par', models.ForeignKey(blank=True, db_column='id_compte_createur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kits_crees', to='adhesion.compte')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='adhesion.formation')),
                ('participants_cibles', models.ManyToManyField(blank=True, related_name='kits_cibles', to='adhesion.participant')),
            ],
            options={
                'db_table': 'KIT',
                'ordering': ['-date_creation'],
            },
        ),
    ]
