# Generated by Django 6.1 on 2026-08-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0014_alter_cohorte_statut_kit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='public_cible',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='statut',
        ),
    ]
