# Generated by Django 6.1 on 2026-08-25 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0015_remove_formation_public_cible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionKit',
            fields=[
                ('id_distribution', models.AutoField(primary_key=True, serialize=False)),
                ('distribue', models.BooleanField(default=False)),
                ('date_distribution', models.DateTimeField(blank=True, null=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='adhesion.kit')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions_kits', to='adhesion.participant')),
                ('remis_par', models.ForeignKey(blank=True, db_column='id_compte_remettant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions_kits_remis', to='adhesion.compte')),
            ],
            options={
                'db_table': 'DISTRIBUTION_KIT',
                'unique_together': {('kit', 'participant')},
            },
        ),
    ]
