# Generated by Django 6.1 on 2026-08-27 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0016_distributionkit'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='fonction_association',
            field=models.CharField(choices=[('PRESIDENT', 'Président(e)'), ('VICE_PRESIDENT', 'Vice-Président(e)'), ('SECRETAIRE_GENERAL', 'Secrétaire Général(e)'), ('TRESORIER', 'Trésorier(ère)'), ('MEMBRE_BUREAU_EXECUTIF', 'Membre du Bureau Exécutif'), ('COORDINATEUR_COMMISSION', 'Coordinateur/trice de Commission'), ('AMBASSADEUR', 'Ambassadeur/drice'), ('MEMBRE_ACTIF', 'Membre Actif'), ('MEMBRE_HONNEUR', "Membre d'Honneur")], default='MEMBRE_ACTIF', max_length=30),
        ),
        migrations.AlterField(
            model_name='membre',
            name='section',
            field=models.ForeignKey(blank=True, db_column='id_section', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membres', to='adhesion.section'),
        ),
    ]
