# Generated by Django 6.1 on 2026-08-27 21:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0017_membre_fonction_association_alter_membre_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionadmin',
            name='code_permission',
            field=models.CharField(choices=[('GERER_MEMBRES', 'Gérer les membres'), ('GERER_EVENEMENTS', 'Gérer les événements'), ('GERER_FORMATIONS', 'Gérer les formations et cohortes'), ('GERER_ACTIONS_SOCIALES', 'Gérer les actions sociales'), ('GERER_CONTROLEURS', 'Gérer les contrôleurs'), ('VOIR_RAPPORTS', 'Voir les rapports et statistiques'), ('IMPORTER_DONNEES', 'Importer des données Excel'), ('GERER_SUIVI', 'Gérer le suivi post-formation'), ('GERER_GOUVERNANCE', 'Gérer la gouvernance (comptes-rendus du bureau)')], max_length=30),
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id_actualite', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('publie_par', models.ForeignKey(db_column='id_compte_auteur', on_delete=django.db.models.deletion.PROTECT, related_name='actualites_publiees', to='adhesion.compte')),
            ],
            options={
                'db_table': 'ACTUALITE',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='CompteRendu',
            fields=[
                ('id_compte_rendu', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('date_reunion', models.DateField()),
                ('contenu', models.TextField()),
                ('decisions', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(db_column='id_compte_createur', on_delete=django.db.models.deletion.PROTECT, related_name='comptes_rendus_crees', to='adhesion.compte')),
            ],
            options={
                'db_table': 'COMPTE_RENDU',
                'ordering': ['-date_reunion'],
            },
        ),
    ]
