# Generated by Django 6.1 on 2026-08-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0018_alter_permissionadmin_code_permission_actualite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionadmin',
            name='code_permission',
            field=models.CharField(choices=[('GERER_MEMBRES', 'Gérer les membres'), ('GERER_EVENEMENTS', 'Gérer les événements'), ('GERER_FORMATIONS', 'Gérer les formations et cohortes'), ('GERER_ACTIONS_SOCIALES', 'Gérer les actions sociales'), ('GERER_CONTROLEURS', 'Gérer les contrôleurs'), ('VOIR_RAPPORTS', 'Voir les rapports et statistiques'), ('IMPORTER_DONNEES', 'Importer des données Excel'), ('GERER_SUIVI', 'Gérer le suivi post-formation'), ('GERER_GOUVERNANCE', 'Gérer la gouvernance (comptes-rendus du bureau)'), ('GERER_COMMUNICATION', 'Gérer la communication (actualités publiques)')], max_length=30),
        ),
    ]
