# Generated by Django 6.1 on 2026-10-08 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adhesion", "0021_jeton_empreinte_expiration_et_securite"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeAction",
            fields=[
                ("id_type_action", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("libelle", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("FORMATION", "Formation / renforcement de capacités"),
                            ("EDUCATION", "Éducation"),
                            ("SANTE", "Santé"),
                            ("URGENCE", "Urgence / catastrophe"),
                            ("ECONOMIE", "Insertion économique"),
                            ("SOCIAL", "Action sociale / dons"),
                            ("INFRASTRUCTURE", "Infrastructure"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=20,
                    ),
                ),
                (
                    "types_cible",
                    models.JSONField(
                        default=list,
                        help_text="Codes de TYPES_CIBLE_CHOICES auxquels ce type d'action s'adresse",
                    ),
                ),
                ("est_formation", models.BooleanField(default=False)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "TYPE_ACTION",
                "ordering": ["libelle"],
            },
        ),
        migrations.AlterField(
            model_name="permissionadmin",
            name="code_permission",
            field=models.CharField(
                choices=[
                    ("GERER_MEMBRES", "Gérer les membres"),
                    ("GERER_EVENEMENTS", "Gérer les événements"),
                    ("GERER_FORMATIONS", "Gérer les formations et cohortes"),
                    ("GERER_ACTIONS_SOCIALES", "Gérer les actions sociales"),
                    ("GERER_CONTROLEURS", "Gérer les contrôleurs"),
                    ("VOIR_RAPPORTS", "Voir les rapports et statistiques"),
                    ("IMPORTER_DONNEES", "Importer des données Excel"),
                    ("GERER_SUIVI", "Gérer le suivi post-formation"),
                    (
                        "GERER_GOUVERNANCE",
                        "Gérer la gouvernance (comptes-rendus du bureau)",
                    ),
                    (
                        "GERER_COMMUNICATION",
                        "Gérer la communication (actualités publiques)",
                    ),
                    (
                        "GERER_REFERENTIELS",
                        "Gérer les référentiels (zones, partenaires, types d'action)",
                    ),
                    ("DONNEES_MEDICALES", "Voir et saisir les données médicales"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                ("id_zone", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=120)),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("REGION", "Région"),
                            ("DEPARTEMENT", "Département"),
                            ("COMMUNE", "Commune"),
                            ("QUARTIER", "Quartier / village"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_zone_parent",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sous_zones",
                        to="adhesion.zone",
                    ),
                ),
            ],
            options={
                "db_table": "ZONE",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Partenaire",
            fields=[
                ("id_partenaire", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=150, unique=True)),
                ("sigle", models.CharField(blank=True, default="", max_length=30)),
                (
                    "type_partenaire",
                    models.CharField(
                        choices=[
                            ("ONG", "ONG / association"),
                            ("ETAT", "Service de l'État"),
                            ("COLLECTIVITE", "Collectivité territoriale"),
                            ("SANTE", "Structure de santé"),
                            ("FORMATION", "Organisme de formation"),
                            ("ENTREPRISE", "Entreprise / secteur privé"),
                            ("BAILLEUR", "Bailleur / fondation"),
                            ("COMMUNAUTAIRE", "Organisation communautaire"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "domaines",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Domaines d'intervention, ex: santé, formation professionnelle",
                        max_length=255,
                    ),
                ),
                (
                    "nom_contact",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("telephone", models.CharField(blank=True, default="", max_length=30)),
                ("email", models.EmailField(blank=True, default="", max_length=150)),
                ("adresse", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_zone",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partenaires",
                        to="adhesion.zone",
                    ),
                ),
            ],
            options={
                "db_table": "PARTENAIRE",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="DefinitionIndicateur",
            fields=[
                ("id_indicateur", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.SlugField(max_length=60)),
                ("libelle", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "type_valeur",
                    models.CharField(
                        choices=[
                            ("ENTIER", "Nombre entier"),
                            ("DECIMAL", "Nombre décimal"),
                            ("MONTANT", "Montant (FCFA)"),
                            ("POURCENTAGE", "Pourcentage"),
                            ("BOOLEEN", "Oui / non"),
                            ("CHOIX", "Choix dans une liste"),
                            ("TEXTE", "Texte"),
                            ("DATE", "Date"),
                        ],
                        max_length=20,
                    ),
                ),
                ("unite", models.CharField(blank=True, default="", max_length=30)),
                (
                    "choix",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Valeurs possibles si type_valeur = CHOIX",
                    ),
                ),
                (
                    "moment",
                    models.CharField(
                        choices=[
                            ("REFERENCE", "Situation de référence (avant)"),
                            ("INTERVENTION", "Intervention"),
                            ("SUIVI", "Suivi"),
                        ],
                        default="INTERVENTION",
                        max_length=20,
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("CIBLE", "Par cible"),
                            ("ACTION", "Pour l'action entière"),
                        ],
                        default="CIBLE",
                        max_length=10,
                    ),
                ),
                ("obligatoire", models.BooleanField(default=False)),
                ("sensible", models.BooleanField(default=False)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                (
                    "type_action",
                    models.ForeignKey(
                        db_column="id_type_action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicateurs",
                        to="adhesion.typeaction",
                    ),
                ),
            ],
            options={
                "db_table": "DEFINITION_INDICATEUR",
                "ordering": ["type_action", "moment", "ordre", "id_indicateur"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("type_action", "code"),
                        name="indicateur_code_unique_par_type",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="zone",
            constraint=models.UniqueConstraint(
                fields=("parent", "niveau", "nom"), name="zone_unique_par_parent"
            ),
        ),
        migrations.AddConstraint(
            model_name="zone",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("niveau", "nom"),
                name="zone_racine_unique",
            ),
        ),
    ]
