# Generated by Django 6.1 on 2026-10-08 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adhesion", "0023_charger_referentiels_initiaux"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionadmin",
            name="code_permission",
            field=models.CharField(
                choices=[
                    ("GERER_MEMBRES", "Gérer les membres"),
                    ("GERER_EVENEMENTS", "Gérer les événements"),
                    ("GERER_FORMATIONS", "Gérer les formations et cohortes"),
                    ("GERER_ACTIONS_SOCIALES", "Gérer les actions sociales"),
                    ("GERER_CONTROLEURS", "Gérer les contrôleurs"),
                    ("VOIR_RAPPORTS", "Voir les rapports et statistiques"),
                    ("IMPORTER_DONNEES", "Importer des données Excel"),
                    ("GERER_SUIVI", "Gérer le suivi post-formation"),
                    (
                        "GERER_GOUVERNANCE",
                        "Gérer la gouvernance (comptes-rendus du bureau)",
                    ),
                    (
                        "GERER_COMMUNICATION",
                        "Gérer la communication (actualités publiques)",
                    ),
                    (
                        "GERER_REFERENTIELS",
                        "Gérer les référentiels (zones, partenaires, types d'action)",
                    ),
                    ("DONNEES_MEDICALES", "Voir et saisir les données médicales"),
                    (
                        "GERER_CIBLES",
                        "Gérer les cibles (personnes, groupes, établissements...)",
                    ),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Cible",
            fields=[
                ("id_cible", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type_cible",
                    models.CharField(
                        choices=[
                            ("PERSONNE", "Personne"),
                            (
                                "GROUPE",
                                "Groupe (GIE, groupement de femmes, groupe de jeunes...)",
                            ),
                            ("ASC", "ASC (association sportive et culturelle)"),
                            (
                                "ETABLISSEMENT",
                                "Établissement (école, poste de santé...)",
                            ),
                            ("ORGANISATION", "Organisation"),
                            ("ZONE_SINISTREE", "Zone sinistrée / localité"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("prenom", models.CharField(blank=True, default="", max_length=100)),
                (
                    "sexe",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        default="",
                        max_length=1,
                    ),
                ),
                ("date_naissance", models.DateField(blank=True, null=True)),
                (
                    "numero_identification",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="CNI ou autre pièce (optionnel)",
                        max_length=50,
                    ),
                ),
                (
                    "sous_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Précision libre : école élémentaire, GIE, groupement de femmes, daara...",
                        max_length=100,
                    ),
                ),
                (
                    "responsable",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "effectif",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Membres, élèves, habitants... selon le type",
                        null=True,
                    ),
                ),
                ("telephone", models.CharField(blank=True, default="", max_length=30)),
                (
                    "telephone_normalise",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "nom_normalise",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        editable=False,
                        max_length=150,
                    ),
                ),
                (
                    "prenom_normalise",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=100
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=150)),
                ("adresse", models.CharField(blank=True, default="", max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "beneficiaire_origine",
                    models.OneToOneField(
                        blank=True,
                        db_column="id_beneficiaire",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cible",
                        to="adhesion.beneficiaire",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_compte_createur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cibles_creees",
                        to="adhesion.compte",
                    ),
                ),
                (
                    "membre",
                    models.OneToOneField(
                        blank=True,
                        db_column="id_membre",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cible",
                        to="adhesion.membre",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_zone",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cibles",
                        to="adhesion.zone",
                    ),
                ),
            ],
            options={
                "db_table": "CIBLE",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="Appartenance",
            fields=[
                (
                    "id_appartenance",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Présidente, élève, trésorier...",
                        max_length=100,
                    ),
                ),
                ("date_debut", models.DateField(blank=True, null=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "collectif",
                    models.ForeignKey(
                        db_column="id_cible_collectif",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membres_collectif",
                        to="adhesion.cible",
                    ),
                ),
                (
                    "personne",
                    models.ForeignKey(
                        db_column="id_cible_personne",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appartenances",
                        to="adhesion.cible",
                    ),
                ),
            ],
            options={
                "db_table": "APPARTENANCE",
            },
        ),
        migrations.AddIndex(
            model_name="cible",
            index=models.Index(
                fields=["type_cible", "nom"], name="CIBLE_type_ci_603793_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="appartenance",
            constraint=models.UniqueConstraint(
                fields=("personne", "collectif"), name="appartenance_unique"
            ),
        ),
    ]
