# Generated by Django 6.1 on 2026-10-08 14:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adhesion", "0026_communes_dakar_unites_parcelles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionadmin",
            name="code_permission",
            field=models.CharField(
                choices=[
                    ("GERER_MEMBRES", "Gérer les membres"),
                    ("GERER_EVENEMENTS", "Gérer les événements"),
                    ("GERER_FORMATIONS", "Gérer les formations et cohortes"),
                    (
                        "GERER_ACTIONS_SOCIALES",
                        "Gérer les actions (et anciennes actions sociales)",
                    ),
                    ("GERER_CONTROLEURS", "Gérer les contrôleurs"),
                    ("VOIR_RAPPORTS", "Voir les rapports et statistiques"),
                    ("IMPORTER_DONNEES", "Importer des données Excel"),
                    ("GERER_SUIVI", "Gérer le suivi post-formation"),
                    (
                        "GERER_GOUVERNANCE",
                        "Gérer la gouvernance (comptes-rendus du bureau)",
                    ),
                    (
                        "GERER_COMMUNICATION",
                        "Gérer la communication (actualités publiques)",
                    ),
                    (
                        "GERER_REFERENTIELS",
                        "Gérer les référentiels (zones, partenaires, types d'action)",
                    ),
                    ("DONNEES_MEDICALES", "Voir et saisir les données médicales"),
                    (
                        "GERER_CIBLES",
                        "Gérer les cibles (personnes, groupes, établissements...)",
                    ),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                ("id_action", models.AutoField(primary_key=True, serialize=False)),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "En préparation"),
                            ("PLANIFIEE", "Planifiée"),
                            ("EN_COURS", "En cours"),
                            ("TERMINEE", "Terminée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="BROUILLON",
                        max_length=10,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("lieu", models.CharField(blank=True, default="", max_length=255)),
                (
                    "budget_prevu",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=14, null=True
                    ),
                ),
                (
                    "budget_realise",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=14, null=True
                    ),
                ),
                ("appel_volontaires", models.BooleanField(default=False)),
                (
                    "volontaires_souhaites",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("bilan", models.TextField(blank=True, default="")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_compte_createur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_creees",
                        to="adhesion.compte",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_membre_responsable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_responsable",
                        to="adhesion.membre",
                    ),
                ),
                (
                    "type_action",
                    models.ForeignKey(
                        db_column="id_type_action",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="adhesion.typeaction",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_zone",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="adhesion.zone",
                    ),
                ),
            ],
            options={
                "db_table": "ACTION",
                "ordering": ["-date_debut", "-id_action"],
            },
        ),
        migrations.CreateModel(
            name="BesoinCible",
            fields=[
                ("id_besoin", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("BASSE", "Basse"),
                            ("MOYENNE", "Moyenne"),
                            ("HAUTE", "Haute"),
                            ("URGENTE", "Urgente"),
                        ],
                        default="MOYENNE",
                        max_length=10,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("IDENTIFIE", "Identifié"),
                            ("PLANIFIE", "Action planifiée"),
                            ("COUVERT", "Couvert"),
                            ("ABANDONNE", "Abandonné"),
                        ],
                        default="IDENTIFIE",
                        max_length=10,
                    ),
                ),
                (
                    "date_identification",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "cible",
                    models.ForeignKey(
                        db_column="id_cible",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="besoins",
                        to="adhesion.cible",
                    ),
                ),
                (
                    "identifie_par",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_compte",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="besoins_identifies",
                        to="adhesion.compte",
                    ),
                ),
                (
                    "type_action",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_type_action",
                        help_text="Type d'action qui y répondrait (facultatif)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="besoins",
                        to="adhesion.typeaction",
                    ),
                ),
            ],
            options={
                "db_table": "BESOIN_CIBLE",
                "ordering": ["statut", "-date_identification"],
            },
        ),
        migrations.CreateModel(
            name="ActionCible",
            fields=[
                (
                    "id_action_cible",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PREVUE", "Prévue"),
                            ("SERVIE", "Servie"),
                            ("ABSENTE", "Absente / non servie"),
                        ],
                        default="PREVUE",
                        max_length=10,
                    ),
                ),
                ("date_intervention", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "action",
                    models.ForeignKey(
                        db_column="id_action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cibles",
                        to="adhesion.action",
                    ),
                ),
                (
                    "cible",
                    models.ForeignKey(
                        db_column="id_cible",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="adhesion.cible",
                    ),
                ),
                (
                    "besoin",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_besoin",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interventions",
                        to="adhesion.besoincible",
                    ),
                ),
            ],
            options={
                "db_table": "ACTION_CIBLE",
            },
        ),
        migrations.CreateModel(
            name="MembreEquipe",
            fields=[
                (
                    "id_membre_equipe",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("role", models.CharField(blank=True, default="", max_length=100)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PROPOSE", "Volontaire, en attente"),
                            ("CONFIRME", "Confirmé"),
                            ("DECLINE", "Non retenu / désisté"),
                        ],
                        default="CONFIRME",
                        max_length=10,
                    ),
                ),
                (
                    "volontaire",
                    models.BooleanField(
                        default=False, help_text="S'est proposé lui-même"
                    ),
                ),
                (
                    "present",
                    models.BooleanField(
                        blank=True, help_text="Présence le jour J", null=True
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.ForeignKey(
                        db_column="id_action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipe",
                        to="adhesion.action",
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        db_column="id_membre",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="adhesion.membre",
                    ),
                ),
            ],
            options={
                "db_table": "MEMBRE_EQUIPE",
            },
        ),
        migrations.CreateModel(
            name="TacheAction",
            fields=[
                ("id_tache", models.AutoField(primary_key=True, serialize=False)),
                ("titre", models.CharField(max_length=200)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("AVANT", "Avant (préparation)"),
                            ("PENDANT", "Pendant"),
                            ("APRES", "Après (clôture, suivi)"),
                        ],
                        default="AVANT",
                        max_length=10,
                    ),
                ),
                ("echeance", models.DateField(blank=True, null=True)),
                ("faite", models.BooleanField(default=False)),
                ("date_faite", models.DateTimeField(blank=True, null=True)),
                (
                    "action",
                    models.ForeignKey(
                        db_column="id_action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taches",
                        to="adhesion.action",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_membre",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taches",
                        to="adhesion.membre",
                    ),
                ),
            ],
            options={
                "db_table": "TACHE_ACTION",
                "ordering": ["faite", "echeance", "id_tache"],
            },
        ),
        migrations.CreateModel(
            name="ValeurIndicateur",
            fields=[
                ("id_valeur", models.AutoField(primary_key=True, serialize=False)),
                (
                    "valeur_nombre",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("valeur_texte", models.TextField(blank=True, default="")),
                ("valeur_booleen", models.BooleanField(blank=True, null=True)),
                ("valeur_date", models.DateField(blank=True, null=True)),
                ("date_saisie", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.ForeignKey(
                        db_column="id_action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valeurs",
                        to="adhesion.action",
                    ),
                ),
                (
                    "action_cible",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_action_cible",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valeurs",
                        to="adhesion.actioncible",
                    ),
                ),
                (
                    "indicateur",
                    models.ForeignKey(
                        db_column="id_indicateur",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valeurs",
                        to="adhesion.definitionindicateur",
                    ),
                ),
                (
                    "saisi_par",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_compte",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="valeurs_saisies",
                        to="adhesion.compte",
                    ),
                ),
            ],
            options={
                "db_table": "VALEUR_INDICATEUR",
            },
        ),
        migrations.CreateModel(
            name="ActionPartenaire",
            fields=[
                (
                    "id_action_partenaire",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("FORMATEUR", "Formateur / opérateur de formation"),
                            ("PRESTATAIRE", "Prestataire (médical, travaux...)"),
                            ("FINANCEUR", "Financeur"),
                            ("SOUTIEN", "Soutien technique ou logistique"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=15,
                    ),
                ),
                (
                    "montant_apport",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=14, null=True
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "action",
                    models.ForeignKey(
                        db_column="id_action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partenaires",
                        to="adhesion.action",
                    ),
                ),
                (
                    "partenaire",
                    models.ForeignKey(
                        db_column="id_partenaire",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participations",
                        to="adhesion.partenaire",
                    ),
                ),
            ],
            options={
                "db_table": "ACTION_PARTENAIRE",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("action", "partenaire"), name="action_partenaire_unique"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="actioncible",
            constraint=models.UniqueConstraint(
                fields=("action", "cible"), name="action_cible_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="membreequipe",
            constraint=models.UniqueConstraint(
                fields=("action", "membre"), name="membre_equipe_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="valeurindicateur",
            constraint=models.UniqueConstraint(
                condition=models.Q(("action_cible__isnull", False)),
                fields=("indicateur", "action_cible"),
                name="valeur_unique_par_cible",
            ),
        ),
        migrations.AddConstraint(
            model_name="valeurindicateur",
            constraint=models.UniqueConstraint(
                condition=models.Q(("action_cible__isnull", True)),
                fields=("indicateur", "action"),
                name="valeur_unique_par_action",
            ),
        ),
    ]
