# Generated by Django 6.0.7 on 2026-08-03 18:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_membre', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('role', models.CharField(default='Militant', max_length=100)),
                ('card_nfc_uid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif / Cotisation à jour'), ('SUSPENDU', 'Suspendu'), ('DESACTIVE', 'Désactivé'), ('PERDU', 'Carte Perdue / Volée')], default='ACTIF', max_length=20)),
            ],
        ),
    ]
